version: 2.1
jobs:
  build:
    docker:
      - image: "dodoesk/firebase-cypress-test-ci:0.2"
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: yarn install && yarn test:ci
